theme: jekyll-theme-hacker
plugins:
 - github-pages
 - jekyll-readme-index

title: [Guides 21]
description: [Материалы для студентов Школы 21]
color: "#20A1BD"
google_analytics: UA-189768467-1
show_downloads: false
relative_links:
  enabled: true
  collections: true
#include:
